### ISSUE TITLE
Discontinuation of RPi builds and Legacy status for current builds.

### ISSUE THREAD

**Issue by GreeneryLover** [LeenuxDev/AmogOS#69]
## Raspberry Pi Builds Discontinued

Effective immediately, the Raspberry Pi/ARM builds of AmogOS are discontinued. This means that they will still be available for download, but support will not be given for them anymore, and issues relating to them will be closed. All references to ARM will soon be removed from the AmogOS repository, and there are no plans to revitalize an ARM build at this time.

There is no longer an effective way to test those builds and guarantee parity with x86_64. Our new aims are much greater, and they cannot be restricted by the underperforming mess of a toolchain we use for Raspberry Pi, AmogOS Pi is plagued by stability and performance issues that we will never be able to solve. There are also package differences and issues with availability for developers and volunteers who are willing to test the OS on real hardware.

## Current x86-64 Builds Entering Legacy Status

At 20:59 GMT, October 11th, AmogOS 2 will be released in Alpha, and the current 1.x.x builds will enter legacy status. This means that they will still receive minor support (e.g, user support, help with installation, etc), but they will no longer receive any updates. If for some bizzare reason you are using AmogOS as an extendable imaged system, your system will stay up-to-date in accordance with the Debian repos and support cycle.

As mentioned before, AmogOS Legacy is being discontinued because of the tech debt it has amounted and the skeletal issues it has accumulated. "Fixing" it completely would be a waste of time, and using a new base where we can actually keep track of changes and share them with the community is a better option. AmogOS 2 will also have custom source code and will be an opportunity for new developers to be brought on board.

## Discord Drama

Nooz/RPi News, the ex-maintainer, is no longer serving in the AmogOS team. His contributions were extremely important, but due to internal disagreements, the organization leader, Autoboy, has decided to replace him. I am now the core developer and current maintainer of AmogOS, and talks are undergoing with developers to make sure we all direct the project in a healthy direction from now on.

Until next time, and with love.

**Comment by mobilegmYT** [comment]
Issue 69 😭

**Comment by Crewmategamingcoding** [comment]
hahaha #69 funny

**Comment by moon1789** [comment]
shut , we **are not gonna discontinue Legacy RPi Builds**

**Comment by buddyjojo** [comment]
uh well the main dev is at least 
you and nooz can work on it though

**Comment by moon1789** [comment]
yes but nooz missing?
